### PR TITLE
Add custom error handling

### PR DESCRIPTION
**Pull request by timomeh**
## Motivation

I like your middleware, it's exactly what I was looking for. However, it handles errors by itself and in case of an error, it sends a static text response. I want my API to always respond with a unified json body.

## Solution

By passing an error to `next`, a middleware can pass an error to a custom express error handler. Reference: http://expressjs.com/en/guide/error-handling.html#writing-error-handlers

Error handling then looks something like this:

```js
app.use((error, req, res, next) => {
  if (error.code === 'ERR_HMAC_AUTH_INVALID') {
    res.status(401).json({
      error: 'Invalid request',
      info: error.message
    })
  } else {
    // handle other errors of your app
  }
})
```

This way I can have full control over handling errors in my app. I can send whatever I want and even capture errors with a service like [Sentry](https://sentry.io/).

I don't want to open a PR with a breaking change, so I made it an opt-in. The middleware will behave the same by default. Setting `options.error = false` will opt you into the "new" error handling. So no breaking changes.

Cheers! 🍻

### CODE REVIEW

**Comment by connorjburton** [comment]
Hey, great PR, much appreciated. I will review today and get back to you with any comments!

**Comment by connorjburton** [comment]
My first thought is to release a breaking change for this, so people who want the existing functionality can stay on `2.x.x`

I am not too keen on a property accepting more than 1 data type and depending which type you pass it has different functionality, this seems confusing for the user.

Just for my reference, creating a `3.0.0` would require the following

- [ ] Tag each version so it's easy for people to see old documentation
- [ ] Update the `README.md`
- [ ] Update the `CHANGELOG.md`
- [ ] Create a `MIGRATION_GUIDE.md`

Happy to hear your thoughts on this, I am happy to finish off this PR, or if you want to do it I am happy with that too!

Again, appreciate the PR

**Comment by connorjburton** [comment]
Sorry, just to clarify. My intention would be to remove the `error` property and use the express recommended way to handle errors. Maybe allow the user to decide what `code` to return?

**Comment by timomeh** [comment]
Of course, if you want to make it a new major, that's totally fine :) I can change it to be a breaking change, update the readme, changelog and migration guide (great thoughts on docs, I really appreciate good docs!). Then you can tag and release it.

I'll change the code now and tell you when I'm finished.

**Comment by timomeh** [comment]
The `error.code` is usually not a configurable option. But I could make it a custom error object with that error code. Then someone can check the error by code or by instance

```js
const { HMACAuthError } = require('hmac-auth-express/src/errors')

app.use((error, req, res, next) => {
  // check by error code, similar to nodejs' native errors
  if (error.code === 'ERR_HMAC_AUTH_INVALID') ...

  // or check by instance, a bit cleaner and similar to other express middlewares
  if (error instanceof HMACAuthError) ...
})
```

**Comment by timomeh** [comment]
Done!

- I removed the backwards compatibility
- I added a custom `HMACAuthError` (bonus: i added `statusCode` keys to the error, which some common error handling libraries use to identify errors) 
- I reflected those changes in the README
- Added it to the changelog as Unreleased change
- Wrote a migration guide

I'm german and my english isn't the best, so please check my wonky english and feel free to correct it 😄

**Comment by connorjburton** [comment]
This is excellent, I will do a full review and complete the PR tomorrow. Thank you so much.

P.S Your English is great

**Comment by connorjburton** [comment]
Merged and released. Good job and thanks!

**Pull request merged**
