### PR TITLE
Allow disable time protection and adjust current time

### PR DESCRIPTION
**Pull request by hectorespert**
- Add option to disable time protection if it is required for debug or test purposes.
- Add option to set time min interval to accept clients that time isn't well synchronized.

### CODE REVIEW

**Comment by connorjburton** [comment]
Hi,

Thanks for the pull request!

1. Could you expand more on this? We have handled this internally by having pre-request script in postman for debugging/testing that generates our HMAC automatically so we don't need to disable this. I am slightly cautious about adding an option to disable it so just want to understand your use case is.

2. Yes we have experienced this too, if the client (computer sending the request) time is slightly ahead of the server, it doesn't have any tolerence and will reject it. This is certainly an addition we want too.

If you could get back to me on point 1 that'd be great, we will also need tests but I am happy to write them, let me know.

Thanks,
Connor

**Comment by connorjburton** [comment]
Sorry, I have seen you have written tests. Thanks!

**Comment by hectorespert** [comment]
> Could you expand more on this? We have handled this internally by having pre-request script in postman for debugging/testing that generates our HMAC automatically so we don't need to disable this. I am slightly cautious about adding an option to disable it so just want to understand your use case is.

I removed option to disable time protection. We don't use it, but it was our first approach to try to fix our problems with clients that aren't well synchronized.
Could you share your postman pre-script to test it? I tried to implement that but I couldn't.

**Comment by james-salloway** [comment]
> Could you share your postman pre-script to test it? I tried to implement that but I couldn't.
```
const body = pm.request.body;
const time = Math.floor(Date.now() / 1000).toString();
const verb = pm.request.method;
const path = '/' + pm.request.url.path.join('/');
const secret = pm.environment.get("hmacSecret");
const hmac = CryptoJS.algo.HMAC.create(CryptoJS.algo.SHA256, secret);

hmac.update(time);
hmac.update(verb);
hmac.update(path);
      
const hmacKey = hmac.finalize().toString();
postman.setEnvironmentVariable('hmacTime', time);
postman.setEnvironmentVariable("hmacKey", hmacKey);
```

@blackleg The hmacTime and hmacKey environment variables are passed to an Authorization header: `Authorization: HMAC {{hmacTime}}:{{hmacKey}}`

If you have any environment variables in your path you'll need to replace these as well.

[Postman Pre-request script docs](https://learning.postman.com/docs/postman/scripts/pre-request-scripts/)

**Comment by connorjburton** [comment]
@blackleg just a note on @Jimsalad post, take note of the unix timestamp as this has changed recently. See migration guide here https://github.com/connorjburton/hmac-auth-express/blob/master/MIGRATION_GUIDE.md#migrating-from-3xx-to-400-2

I will review your pull request today or tomorrow, thanks!

**Comment by hectorespert** [comment]
@Jimsalad @connorjburton thanks a lot

**Comment by connorjburton** [comment]
Sorry for the slow action, will get this released onto NPM this weekend

**Comment by connorjburton** [comment]
Thank you very much for the pull request by the way.

**Pull request merged**
